### ISSUE TITLE
make additional information z optional

### ISSUE THREAD

**Issue by thorek1** [gdalle/ImplicitDifferentiation.jl#54]
what about making z optional? 

I see benefits in cleaner and more concise code when writing up forward and condition functions and possibly minor speed gains

**Comment by gdalle** [comment]
While the additional information was not present in earlier versions of the library, we realized it is essential for more advanced uses like [differentiable Frank-Wolfe](https://github.com/gdalle/DifferentiableFrankWolfe.jl). It can also help when `forward` is an optimization procedure which generates interesting byproducts like Jacobians. This rationale should probably be mentioned in the docs, now that I think about it :)

The trouble with making it optional is that we would have a static uncertainty on the number of outputs for `forward` / number of inputs for `conditions`. This would cause runtime dispatch, so I'm unsure about the speed benefits.

If you don't want it, you can simply `return y, 0` instead of `return y`, and add an unused argument to `conditions`. I think for now it will stay that way, but if you have a proposal on how to avoid runtime dispatch I'm all ears!

**Comment by mohamed82008** [comment]
We can solve this issue using a compile time flag in `ImplicitFunction` and internal types `Conditions` and `Forward`.
```julia
(f::Forward{true})(x; kwargs...) = f.forward(x, kwargs...)
(f::Forward{false})(x; kwargs...) = f.forward(x, kwargs...), 0

(f::Conditions{true})(x, y, z; kwargs...) = f.condition(x, y, z, kwargs...)
(f::Conditions{false})(x, y, _; kwargs...) = f.conditions(x, y, kwargs...)
```
If users say `ImplicitFunction(forward, conditions, Val(false))`, we construct `Conditions{false}` and `Forward{false}` internally and wrap them in the `ImplicitFunction` struct. The default value can be `Val(false)`.
